language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3

before_install:
    - git clone https://github.com/samtools/htslib.git
    - sudo make -C htslib
    - git clone https://github.com/samtools/samtools.git
    - sudo make -C samtools
    - sudo cp samtools/samtools $HOME/bin
    - sudo cp samtools/misc/wgsim $HOME/bin
    - git clone https://github.com/samtools/bcftools.git
    - sudo make -C bcftools
    - sudo cp bcftools/bcftools $HOME/bin
    - git clone https://github.com/lh3/bwa.git
    - sudo make -C bwa
    - sudo cp bwa/bwa $HOME/bin
    - wget https://github.com/broadinstitute/picard/releases/download/1.131/picard-tools-1.131.zip
    - unzip picard-tools-1.131.zip
    - git clone https://github.com/adamewing/exonerate.git
    - cd exonerate
    - sudo ./configure && make && make install
    - wget https://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz
    - tar xvzf velvet_1.2.10.tgz
    - sudo make -C velvet_1.2.10
    - sudo cp velvet_1.2.10/velvetg $HOME/bin
    - sudo cp velvet_1.2.10/velveth $HOME/bin
    - sudo pip install cython
    - sudo pip install pysam

install: true
script:
    # Get out of the source directory before running tests to avoid PYTHONPATH
    # confusion.  This is necessary to ensure that the speedups module can
    # be found in the installation directory.
    - cd bamsurgeon
    # Copy the coveragerc down so coverage.py can find it.
    - python setup.py build
    - python setup.py install
